base_frame_id: base_link
first_map_only: false
global_frame_id: map


max_particles: 500
min_particles: 100
resample_interval: 1

kld_err: 0.01
kld_z: 0.99

update_min_a: 0.1
update_min_d: 0.1

recovery_alpha_fast: 0.1
recovery_alpha_slow: 0.01

laser_z_hit: 0.9
laser_z_max: 0.025
laser_z_rand: 0.025
laser_z_short: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1

laser_likelihood_max_dist: 4.0

laser_model_type: beam
laser_max_beams: 250
laser_max_range: -1.0
laser_min_range: -1.0

odom_model_type: diff-corrected
odom_alpha1: 0.01
odom_alpha2: 0.01
odom_alpha3: 0.005
odom_alpha4: 0.005

odom_alpha5: 0.1

beam_skip_distance: 0.5
beam_skip_threshold: 0.3
do_beamskip: false

gui_publish_rate: 10.0
gui_publish_rate: 10.0
transform_tolerance: 0.1
id: 0
save_pose_rate: 0.5

name: Default
odom_frame_id: odom
parent: 0
restore_defaults: false
state: true
tf_broadcast: true
type: ''
use_map_topic: false
